schema_version: 1

context:
  name: cWB
  version: 6.4.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gitlab.com/gwburst/public/library/-/archive/${{ version }}/library-${{ version }}.tar.gz
  sha256: 9dc101cb906749c5cc271b151db1db96d29cfcb6ff59e77cdb676097afc75dff
  patches:
    # Forward-port changes from https://gitlab.com/gwburst/public/library/-/commits/public_xhtml
    # relative to 504bc84678f78266538f94a5ff2f75e83b953e1d
    - patches/0001-Cherry-pick-.-src-root-html-from-the-ROOT-source-to-.patch
    - patches/0002-added-xTDocInfo-class-to-xhtml-library.patch
    - patches/0003-add-pragma-link-C-class-xTDocDirective.patch
    - patches/0004-added-more-xTDoc.-streamers.patch
    - patches/0005-Minor-changes.patch
    - patches/0006-First-implementation-of-the-xTHtml-class.patch
    # fix plain vs keyword target_link_libraries mixing
    - patches/0007-Fix-mixing-plain-and-keyword-target_link_libraries-s.patch

build:
  number: 5
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - if: build_platform != target_platform
      then: root_base
  host:
    - healpix_cxx >=3.80
    - libframel
    - liblal
    - liblalburst
    - liblalmetaio
    - liblalsimulation
    - root_base
    - root_cxx_standard
  run:
    - root_base
    - tcsh
    - uproot <=4.3.7
    - xgboost <=1.7.6
  run_exports:
    - ${{ pin_subpackage(name|lower, upper_bound='x.x.x') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/cwb${SHLIB_EXT}
      - test -f ${PREFIX}/include/cwb.hh
      - cwb_help
      - cwb_watenv verbose
      - ComputeWDMFourier
      - root ${CWB_ROOTLOGON_FILE} -e '.q'

about:
  summary: "cWB pipeline library"
  description: |
    Coherent network analysis is addressing the problem of detection and
    reconstruction of gravitational waves (GW) with networks of detectors.
    It has been extensively studied in the literature in application to
    detection of bursts signals, which may be produced by numerous
    gravitational wave sources in the Universe.
    In coherent methods, a statistic is built up as a coherent sum over
    detector responses.
    In general, it is expected to be more optimal (better sensitivity
    at the same false alarm rate) than the detection statistics of the
    individual detectors that make up the network.
    Also coherent methods provide estimators for the GW waveforms and
    the source coordinates in the sky.

    The method we present (called coherent WaveBurst) is significantly
    different from the traditional burst detection methods.
    Unlike coincident methods, which first identify events in individual
    detectors by using an excess power statistic and than require
    coincidence between detectors, the coherent WaveBurst method combines
    all data streams into one coherent statistic constructed in the
    framework of the constrained maximum likelihood analysis.
    Such an approach has significant advantages over the coincident methods.
    First, the sensitivity of the method is not limited by the least
    sensitive detector in the network.
    In the coherent WaveBurst method the detection is based on the maximum
    likelihood ratio statistic which represents the total signal-to-noise
    ratio of the GW signal detected in the network.
    Second, other coherent statistics, such as the null stream and the
    network correlation coefficient can be constructed to distinguish
    genuine GW signals from the environmental and instrumental artifacts.
    Finally, the source coordinates of the GW waveforms can be reconstructed.
  homepage: https://gitlab.com/gwburst/public/library
  repository: https://gitlab.com/gwburst/public/library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ceccozzi
    - duncanmmacleod
